/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Daniel Teixeira
 */
public class Janela extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public Janela(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valor1 = new javax.swing.JTextField();
        opcoes = new javax.swing.JComboBox<>();
        saida = new javax.swing.JTextField();
        imagem = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        valor2 = new javax.swing.JTextField();
        enter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aritmética Binária");
        setResizable(false);

        opcoes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-" }));

        saida.setEditable(false);
        saida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saidaActionPerformed(evt);
            }
        });

        imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img.png"))); // NOI18N

        enter.setText("=");
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(saida, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(opcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(valor1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(valor2)))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(enter))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(imagem)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(valor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(opcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addComponent(enter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saidaActionPerformed

    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed
        if (this.opcoes.getSelectedIndex() == 0) {    //SOMA
            
            System.out.println("SOMA");
            
            String v1 = valor1.getText();
            String v2 = valor2.getText();
            String valor_saida = "";
            int transbordo = 0;

            for (int pos = v1.length() - 1; pos >= 0; pos--) {
                int num1 = Integer.parseInt(String.valueOf(v1.charAt(pos)));
                int num2 = Integer.parseInt(String.valueOf(v2.charAt(pos)));

                // caso das soma de 0+0
                if (transbordo + num1 + num2 == 0) {
                    valor_saida = "0" + valor_saida;
                    transbordo = 0;

                    continue;
                }

                // caso das soma de 0+1 ou 1+0
                if (transbordo + num1 + num2 == 1) {
                    valor_saida = "1" + valor_saida;
                    transbordo = 0;

                    continue;
                }

                // caso das soma de 1+1
                if (transbordo + num1 + num2 == 2) {
                    valor_saida = "0" + valor_saida;
                    transbordo = 1;

                    continue;
                }

                // caso das soma de 1+1+1
                if (transbordo + num1 + num2 == 3) {
                    valor_saida = "1" + valor_saida;
                    transbordo = 1;

                    continue;
                }
            }

            // caso ainda exista Transbordo
            if (transbordo == 1) {
                valor_saida = "1" + valor_saida;
            }

            saida.setText(valor_saida);

        } else {                                      //SUBTRAÇÃO
            
            System.out.println("SUBTRAÇÃO");
            
            String v1 = valor1.getText();
            String v2 = valor2.getText();
            String valor_saida = "";
            String max="";
            char b='0';
            boolean tf=(v1.length()>=v2.length());
            int n1=v1.length();
            int n2=v2.length();
            
            if(n1<n2)
            for(int a=1;a<=n2-n1;a++)
            v1='0'+v1;

            else if(n2<n1)
            for(int a=1;a<=n1-n2;a++)
            v2="0"+v2;
            if(!tf)for(int a=n1-1;a>=0;a--)
            if(v1.charAt(a)!=v2.charAt(a))
            if(v2.charAt(a)=='1'){max=v2;v2=v1;v1=max;break;}

            for(int a=v1.length()-1;a>=0;a--)
            {
                if(v1.charAt(a)=='1' && v2.charAt(a)=='0')
                {
                    if(b=='1')
                    {valor_saida='0'+valor_saida;b='0';}
                    else
                    valor_saida='1'+valor_saida;
                }

                else if(v1.charAt(a)==v2.charAt(a) && v2.charAt(a)=='1')
                {
                    if(b=='1')
                   {valor_saida='1'+valor_saida;b='1';}
                    else
                    valor_saida='0'+valor_saida;
                }

                else if(v1.charAt(a)=='0' && v2.charAt(a)=='1')
                {
                    if(b=='1')
                    valor_saida='0'+valor_saida;
                    else
                    {valor_saida='1'+valor_saida;b='1';}
                }

                else
                {
                    if(b=='1')
                    valor_saida='1'+valor_saida;
                    else
                    valor_saida='0'+valor_saida;
                }
            }
             saida.setText(valor_saida);
        }
    }//GEN-LAST:event_enterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Janela dialog = new Janela(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enter;
    private javax.swing.JLabel imagem;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> opcoes;
    private javax.swing.JTextField saida;
    private javax.swing.JTextField valor1;
    private javax.swing.JTextField valor2;
    // End of variables declaration//GEN-END:variables
}
